version: "3"

services:
  etl:
    image: pennsieve/job-scheduling-service:latest
    ports:
      - 8080:8080
    environment:
      - CLOUDWRAP_ENVIRONMENT=local
      - JWT_SECRET_KEY=secret
      - ETL_POSTGRES_HOST=postgres
      - ETL_POSTGRES_USER=postgres
      - ETL_POSTGRES_PASSWORD=password
    depends_on:
      - postgres
  postgres:
    hostname: postgres
    image: postgres:9.5.10
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
